#!/usr/bin/env ansible-playbook
---

- hosts: all:!localhost
  become: true
  gather_facts: true

  pre_tasks:
    - name: Register RHEL 8
      redhat_subscription:
        state: present
        username: "{{ lookup('env','RH_USER') }}"
        password: "{{ lookup('env','RH_PASS') }}"
        syspurpose:
          role: "Red Hat Enterprise Server"
          usage: "Development/Test"
          service_level_agreement: "Self-Support"
      tags:
        - register

    - name: Update packages
      yum:
        name: "*"
        state: latest
      tags:
        - update

  roles:
    - {role: ssh_keys, tags: ssh_keys}

- hosts: automationcontroller
  become: true
  gather_facts: true

  pre_tasks:

    - name: Set vars
      set_fact:
        registry_username: "{{ lookup('env','RH_USER') }}"
        registry_password: "{{ lookup('env','RH_PASS') }}"

  roles:
    - {role: aap, tags: aap}

...
